blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blogs.urls', namespace='blogs')),

]

blogs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^blog/edit/(?P<blog_id>[0-9]+)$', views.editEntity, name='editEntity'),

    url(r'^blog/(?P<blog_id>[0-9]+)$', views.blog, name='blog'),

    url(r'^addEntity/$', views.addEntity, name='addEntity'),

    url(r'^newEntity/$', views.newEntity, name='newEntity'),

    url(r'^blog/delete/(?P<blog_id>[0-9]+)$', views.deleteBlog, name='deleteEntity'),

    url(r'^manageBlog/$', views.manageBlog, name='manageBlog'),
]

blogs/models.py
# Create your models here.

from django.db import models

class Topic(models.Model):
    topic = models.CharField(u'主题', max_length=30)






class Blog(models.Model):
    id = models.IntegerField(primary_key=True)
    author = models.CharField(u'作者', max_length=30)
    topic = models.ForeignKey(Topic)
    createTime = models.DateTimeField(u'发布时间', auto_now_add=True, editable=True)
    updateTime = models.DateTimeField(u'更新时间', auto_now=True, null=True)
    content = models.TextField(u'内容', max_length=256)
    title = models.TextField(u'标题',)
    def __str__(self):
        return self.title




class Person(models.Model):
    firstName = models.CharField(u'姓',max_length=30)
    lastName = models.CharField(u'名', max_length=30)

    def myProperty(self):
        return self.firstName+' '+self.lastName
    myProperty.shortDescription="full name of the person"

    fullName = property(myProperty)

blogs/forms.py
# 表单

from django import forms

from blogs.models import Blog


class BlogEntity(forms.ModelForm):
    # Meta类是告诉Django根据哪个模型创建表单，以及在表单中包含哪些字段
    class Meta:
        model = Blog
        fields = ['title', 'content']

        # labels = {'title': '标题', 'content': '内容'}

        widgets = {'title': forms.TextInput(attrs={'type': 'text'}), 'content': forms.Textarea(attrs={'cols': 40})}

blogs/views.py
# coding:utf-8
from django.http import HttpResponseRedirect
from django.shortcuts import render
import time

# Create your views here.
from django.urls import reverse

from blogs.forms import BlogEntity
from blogs.models import Blog


def home(request):
    return render(request, 'blogs/home.html')


def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    context = {'blog': blog}
    return render(request, 'blogs/blog.html', context)


# 进入添加Blog页面
def addEntity(request):
    from blogs.forms import BlogEntity
    form = BlogEntity
    return render(request, reverse('blogs:'))


# 添加blog
def newEntity(request):
    if request.method == 'POST':
        form = BlogEntity(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            title = str(title)
            content = str(content)
            createTime = time.strftime('%Y-%m-%d-%H-%M-%S', time.localtime(time.time()))
            updateTime = createTime
            from blogs.models import Blog
            Blog.objects.create(title=title, content=content, createTime=createTime, updateTime=updateTime, )
            return HttpResponseRedirect(reverse('blogs:manageBlog'))
    else:
        form = BlogEntity()
        return render(request, 'blogs/newEntity.html', {'form': form})


# edit
def editEntity(request, blog_id):
    from .models import Blog
    if request.method == 'POST':
        form = BlogEntity(request.POST)
        if form.is_valid():
            blog = Blog.objects.get(id=blog_id)
            blog.title = form.cleaned_data.get('title')
            blog.content = form.cleaned_data.get('content')
            blog.updateTime = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))
            # title = str(title)
            # content = str(content)
            blog.save()
            return HttpResponseRedirect(reverse('blogs:blog', kwargs={'blog_id': blog_id}))
    else:

        blog = Blog.objects.get(id=blog_id)
        form = BlogEntity(initial={'title': blog.title, 'content': blog.content})
        context = {'form': form, 'blog': blog}
        return render(request, 'blogs/editEntity.html', context)


def deleteBlog(request,blog_id):
    from blogs.models import Blog
    Blog.objects.get(id=blog_id).delete()
    return HttpResponseRedirect(reverse('blogs:manageBlog'))


def selectBlog(request, blog_id):
    pass


def manageBlog(request):
    from blogs.models import Blog
    blogs = Blog.objects.all()
    return render(request, 'blogs/manage_blog.html', {'blogs': blogs})

blogs/templates/blogs/base.html
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}默认标题{% endblock %}</title>
    {#    html相对路径  返回上一目录../，根目录 /  ，当前目录  ./#}
    {% block head %}
    {% endblock head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
</head>
<body>
<div class="header">
    <div>
        <h1>zqxdreams's Blog</h1>
    </div>

    <div style="position: absolute;right: 10px;top: 10px;">
        <audio controls id="audio_play_music">
            <source src="/blogs/static/music/川井憲次%20-%20TOMORROW%20~第14话エンディングテーマ~.mp3" type="audio/mpeg">
            您的浏览器不支持 audio 元素。
        </audio>
    </div>
    <div class="div_nav">
        <nav class="blog_nav">
            <ul>
                <li><a href="{% url 'blogs:home' %}">Home</a></li>
                <li><a href="https://github.com/AXNshy">Github</a></li>
                <li><a href="{% url 'blogs:manageBlog' %}">Manage</a></li>
            </ul>
        </nav>
    </div>
</div>
{% block content %}

{% endblock content %}
</body>
</html>

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block head %}
    <link rel="stylesheet" href="/blogs/static/css/blog.css">
{% endblock %}

{% block content %}
    <div class="blog_content">
        <h3>{{ blog.title }}</h3>
        <p>{{ blog.content|safe|linebreaks }}</p>
    </div>
{% endblock content %}

blogs/templates/blogs/editEntity.html
{% extends 'blogs/base.html' %}
{% load static %}
{% block title %}
    {{ blog.title }}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/blogForm.css' %}"/>
{% endblock %}

{% block content %}
    <form action="{% url 'blogs:editEntity' blog.id%}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="提交">
    </form>
{% endblock %}

blogs/templates/blogs/home.html
{% extends 'blogs/base.html' %}

{% block title %}AXNshy的Blog
{% endblock %}

{% block content %}

{% endblock content %}

blogs/templates/blogs/manage_blog.html
{% extends 'blogs/base.html' %}
{% block head %}
    <link rel="stylesheet" href="/blogs/static/css/manageBlog.css" type="text/css">
{% endblock %}

{% block title %}
    Blog Manage
{% endblock %}

{% block content %}
    <div class="blog_list">
        {% for blog in blogs %}
            <p class="blog_list_item">
                <a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {{ blog.createTime }}
                <br><br><br>
                <a href="{% url 'blogs:editEntity' blog.id %}">编辑</a>
                <a href="{% url 'blogs:deleteEntity' blog.id %}">删除</a>
            </p>
            <br>
        {% empty %}
            <p style="color: #FFF;">还没有blog，快去写一篇吧！！！</p>
        {% endfor %}
        <div>
            <div class="write_button">
                <a href="{% url 'blogs:newEntity' %}">写Blog</a>
            </div>
        </div>

    </div>{% endblock %}

blogs/templates/blogs/newEntity.html
{% extends 'blogs/base.html' %}
{% load static %}
{% block title %}
    写Blog
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/blogForm.css' %}"/>
{% endblock %}



{% block content %}
    <form action="{% url 'blogs:newEntity' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input name="submit" type="submit" value="保存">
    </form>
{% endblock %}